# testing
bag_extractor:
  ros__parameters: 
    rate: "10"
    
    # bag_name: "e_1_test"
    # bag_name: "e_2_test"
    # bag_name: "e_2_test2"
    # bag_name: "e_2_train"
    # bag_name: "e_3_test"
    # bag_name: "e_4_train"
    # bag_name: "e_4_train2"
    # bag_name: "e_4_train3"
    # bag_name: "e_4_train4"
    # bag_name: "e_4_test4"
    # bag_name: "e_5_test"
    # bag_name: "levineT_1_bag"
    # bag_name: "PP 1"
    # bag_name: "pp_lobby_1"
    # bag_name: "sim2real_2"
    # bag_name: "sim2real_3"
    # bag_name: "sim2real_lobby"
    # bag_name: "superP_run1working"
    # bag_name: "superT_bag"
    # bag_name: "supervisor_lobby_v2"
    # bag_name: "t1_lobby_train"
    # bag_name: "t1_train_v3"
    # bag_name: "t2_1_random_super_test"
    # bag_name: "t2_1_train"
    # bag_name: "t2_1_train2"
    ###### bag_name: "t2_11_train"
    bag_name: "test9"
    # bag_name: "test_agent10"
    # bag_name: "testing_4"
    # bag_name: "testing_6"
    # bag_name: "testing_onBoardA_1"
    # bag_name: "testing_onBoardA_2"
    # bag_name: "train_agent10"
    ##### bag_name: "train_agent11"
    # bag_name: "training5"
    # bag_name: "training7"
    # bag_name: "training_4"
    # bag_name: "training_4a2"
    # bag_name: "train_onB_3"
    # bag_name: "train_onBActual_3"
    # bag_name: "ex4_on_lobby_test"


