# testing

safety_trainer:
  ros__parameters: 
    agent_name: "PaperSafetyAgent_1"
    # agent_name: "TestingAgent_1"

    map_name: "levine_blocked"
    # map_name: "columbia_small"
    n_laps: 2

pure_pursuit:
  ros__parameters: 
    map_name: "levine_2nd"
    # map_name: "levine_blocked"
    # map_name: "columbia_small"
    n_laps: 10
    
    supervision: True
    # supervision: False

agent_tester:
  ros__parameters:
    n_laps: 2
    agent_name: "PaperSafetyAgent_1"


gap_follow:
  ros__parameters: 
    map_name: "levine_2nd"
    # map_name: "levine_blocked"
    # map_name: "columbia_small"
    n_laps: 10
    
    supervision: True
    # supervision: False


gap_follow:
  ros__parameters: 
    map_name: "levine_2nd"
    # map_name: "columbia_small"
    n_laps: 10
    
    # supervision: True
    supervision: False


rando_plan:
  ros__parameters: 
    n_laps: 10
    # map_name: "columbia_small" # for supervisor
    map_name: "levine_blocked"
    

